####
# Imagen nativa (GraalVM / Mandrel). Construir el binario antes:
#
#   ./mvnw -DskipTests -Dnative -Dquarkus.native.container-build=true package
#
# Imagen:
#
#   source ../../deployment/sp-demo-images.env.sh
#   podman build -f src/main/docker/Dockerfile.native -t "${SP_IMAGE_EDGE_MANAGER_NATIVE}" .
#
# Ejecución local:
#
#   podman run --rm -p 8080:8080 "${SP_IMAGE_EDGE_MANAGER_NATIVE}"
#
####
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/manager-1.0.0-runner /work/application
RUN chmod +x /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
